name: tendly
description: Tendly — your parenting companion. Grow together, every day.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  supabase_flutter: ^2.3.0
  purchases_flutter: ^6.25.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
